# Copyright (C) The DDC development team, see COPYRIGHT.md file
#
# SPDX-License-Identifier: MIT

name: Tests on macOS 2

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
jobs:
  test-macos:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-14, macos-15]
    runs-on: ${{matrix.os}}
    env:
      Kokkos_ROOT: ${{github.workspace}}/my_opt/kokkos
      paraconf_ROOT: ${{github.workspace}}/my_opt/paraconf
      PDI_ROOT: ${{github.workspace}}/my_opt/pdi
      spdlog_ROOT: ${{github.workspace}}/my_opt/spdlog
      yaml_ROOT: ${{github.workspace}}/my_opt/yaml
      CMAKE_PREFIX_PATH: ${{github.workspace}}/my_opt/pdi
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      CC: clang
      CXX: clang++
      CMAKE_BUILD_TYPE: Debug
    steps:
    - run: brew install mpich
    - uses: actions/checkout@v4
    - name: Install PDI+user code plugin and dependencies
      run: |
        git config --global --add safe.directory '*'

        git clone --branch 0.2.5 --depth 1 https://github.com/yaml/libyaml.git yaml
        cmake -DBUILD_SHARED_LIBS=ON -B yaml-build -S yaml
        cmake --build yaml-build
        cmake --install yaml-build --prefix $yaml_ROOT

        git clone --branch 1.0.0 --depth 1 https://github.com/pdidev/paraconf.git paraconf
        cmake -DBUILD_SHARED_LIBS=ON -DBUILD_FORTRAN=OFF -DUSE_DEFAULT=SYSTEM -B paraconf-build -S paraconf
        cmake --build paraconf-build
        cmake --install paraconf-build --prefix $paraconf_ROOT

        git clone --branch v1.13.0 --depth 1 https://github.com/gabime/spdlog.git spdlog
        cmake -DBUILD_SHARED_LIBS=ON -B spdlog-build -S spdlog
        cmake --build spdlog-build
        cmake --install spdlog-build --prefix $spdlog_ROOT

        git clone --branch 1.8.3 --depth 1 https://github.com/pdidev/pdi.git
        mv *.patch pdi/
        git -C pdi apply fix_aligned_alloc.patch fix_integer_types.patch fix_user_code.patch
        cmake \
          -DBUILD_BENCHMARKING=OFF \
          -DBUILD_DOCUMENTATION=OFF \
          -DBUILD_FORTRAN=OFF \
          -DBUILD_TESTING=OFF \
          -DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations -Wno-unqualified-std-cast-call" \
          -DCMAKE_CXX_STANDARD=17 \
          -DCMAKE_GTEST_DISCOVER_TESTS_DISCOVERY_MODE=PRE_TEST \
          -DENABLE_ZSH=OFF \
          -B build-pdi \
          -S pdi/pdi
        cmake --build build-pdi
        cmake --install build-pdi --prefix $PDI_ROOT
        ctest --test-dir build-pdi --output-on-failure
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
    - name: Plugins
      run: |
        export DYLD_LIBRARY_PATH=$paraconf_ROOT/lib:$spdlog_ROOT/lib:$yaml_ROOT/lib

        cmake \
          -DBUILD_FORTRAN=OFF \
          -DBUILD_TESTING=ON \
          -DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations -Wno-unqualified-std-cast-call" \
          -DCMAKE_CXX_STANDARD=17 \
          -DCMAKE_GTEST_DISCOVER_TESTS_DISCOVERY_MODE=PRE_TEST \
          -B build-plugins-mpi \
          -S pdi/plugins/mpi
        cmake --build build-plugins-mpi
        ctest --test-dir build-plugins-mpi --output-on-failure

        cmake \
          -DBUILD_TESTING=ON \
          -DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations -Wno-unqualified-std-cast-call" \
          -DCMAKE_CXX_STANDARD=17 \
          -DCMAKE_GTEST_DISCOVER_TESTS_DISCOVERY_MODE=PRE_TEST \
          -B build-plugins-serialize \
          -S pdi/plugins/serialize
        cmake --build build-plugins-serialize
        ctest --test-dir build-plugins-serialize --output-on-failure

        cmake \
          -DBUILD_TESTING=ON \
          -DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations -Wno-unqualified-std-cast-call" \
          -DCMAKE_CXX_STANDARD=17 \
          -DCMAKE_GTEST_DISCOVER_TESTS_DISCOVERY_MODE=PRE_TEST \
          -B build-plugins-set_value \
          -S pdi/plugins/set_value
        cmake --build build-plugins-set_value
        ctest --test-dir build-plugins-set_value --output-on-failure

        cmake \
          -DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations -Wno-unqualified-std-cast-call" \
          -DCMAKE_CXX_STANDARD=17 \
          -B build-plugins-trace \
          -S pdi/plugins/trace
        cmake --build build-plugins-trace
        ctest --test-dir build-plugins-trace --output-on-failure

        cmake \
          -DBUILD_TESTING=ON \
          -DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations -Wno-unqualified-std-cast-call" \
          -DCMAKE_CXX_STANDARD=17 \
          -DCMAKE_GTEST_DISCOVER_TESTS_DISCOVERY_MODE=PRE_TEST \
          -B build-plugins-user_code \
          -S pdi/plugins/user_code
        cmake --build build-plugins-user_code
        ctest --test-dir build-plugins-user_code --output-on-failure
    - run: |
        git clone --branch 4.5.01 --depth 1 https://github.com/kokkos/kokkos.git
        cmake \
          -DBUILD_SHARED_LIBS=ON \
          -DCMAKE_CXX_STANDARD=17 \
          -DKokkos_ENABLE_DEPRECATED_CODE_4=OFF \
          -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF \
          -DKokkos_ENABLE_SERIAL=ON \
          -B build-kokkos \
          -S kokkos
        cmake --build build-kokkos
        cmake --install build-kokkos --prefix $Kokkos_ROOT
        cmake -B build
        cmake --build build
        cmake --install build --prefix test
    - name: Inspect PDI library
      run: |
        otool -l $PDI_ROOT/lib/libpdi.1.dylib
        otool -l $Kokkos_ROOT/lib/libkokkoscore.dylib
    - name: Inspect binaries
      run: |
        otool -l ./build/main
        otool -l ./test/bin/main
    - name: Run test
      run: |
        echo "Before sourcing env.sh"
        DYLD_PRINT_LIBRARIES=1 ./build/main || true
        ./test/bin/main || true
        . $PDI_ROOT/share/pdi/env.sh
        echo "After sourcing env.sh"
        ./build/main || true
        ./test/bin/main || true
